name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: | 
            echo "Hello world"
            echo "second output"
      - name: print goodbye
        run: echo "good bye"
